### ISSUE TITLE
A useful plug-in!

### ISSUE THREAD

**Issue by DutchPete** [mnaoumov/obsidian-better-markdown-links#1]
A useful plug-in. I have always been concerned about the use of wikilinks because not all markdown apps support them, although that seems to be increasing. But even if an app supports them, like Obsidian does, real markdown links like the ones created by this plug-in will work in any markdown app.
Thank you.

**Comment by DylanIerley** [comment]
Thank you! I've been manually converting links and it's a massive pain this is a huge help!

**Comment by DutchPete** [comment]
Take your time, it is important to get it done well, even if slowly, because we don't want our non-md file links to get messed up 😀

**Comment by mnaoumov** [comment]
@DutchPete I don't get it. What do I need to take my time for?

**Comment by DutchPete** [comment]
@mnaoumov I got my knickers in a twist, somehow mistaking Dylan for you, and I thought you were actually replying to issue #2 that I submitted.
I apologize for the misunderstanding, it is my fault entirely.
