### ISSUE TITLE
[BUG]Incorrect link name conversion

### ISSUE THREAD

**Issue by EpicJayQQ753285662** [mnaoumov/obsidian-better-markdown-links#10]
After using this plugin, some links may be converted to this format
![image](https://github.com/user-attachments/assets/ac5c5a1b-1fb6-4709-89a4-249f91338f9c)
After using the links plugin to convert to MD format, it causes the nested link names to be too long
![image](https://github.com/user-attachments/assets/6a4214c0-9681-4d5b-86f1-8db314f1f6d8)
At this point, I need to manually delete the link name to automatically correct it, which is too troublesome
![image](https://github.com/user-attachments/assets/6dd7dc24-4197-42ee-beff-b4ace1aa5f00)
Request to fix this issue

**Comment by mnaoumov** [comment]
@EpicJayQQ753285662 you didn't follow the bug template

**Comment by EpicJayQQ753285662** [comment]
Also, it has been converted into an incorrect format, and I will also make the necessary modifications once I detect it again

**Comment by EpicJayQQ753285662** [comment]
> @EpicJayQQ753285662 you didn't follow the bug template

what?

**Comment by mnaoumov** [comment]
![image](https://github.com/user-attachments/assets/fb606148-c3a5-4ff3-89c4-ec504391a03e)
