### ISSUE TITLE
[FR] Markdown Links for Selected Directories Only

### ISSUE THREAD

**Issue by zak-admin** [mnaoumov/obsidian-better-markdown-links#11]
### Description

I prefer to use Wiki Links by default and use Markdown Links within specific directory, which can most probably be a markdown documentation I manage for github or any other... 

In short **Markdown Links for Selected Directories Only**, This means I should not need to disable Wikilinks and change to relative path. It must be the default, anyway for that selected directories, the plugin will need to work on

### Details

1. Go to 'Better Markdown Links Plugin Settings'
2. Select 'Entire Vault or Selected Directories'
3. If it is 'Selected Directories' specify them
4. Finally Start Better Markdown Links Plugin to take effect
...

### Desired Behavior

Automatic Markdown links to selected Directories only.

### Current Behavior

Automatic Markdown links to entire Vault.

### Attachments

- Please attach a video showing the current behavior
- Please attach a sample vault where the desired Feature Request could be applied

### Confirmations

- [X] I attached a video showing the current behavior
- [X] I attached a sample vault where the desired Feature Request could be applied
- [X] I have tested the issue with the latest version
- [X] I have checked for existing Feature Requests

**Comment by mnaoumov** [comment]
Added in https://github.com/mnaoumov/obsidian-better-markdown-links/releases/tag/2.10.0
