### ISSUE TITLE
[BUG] Links do not update after moving file to another directory

### ISSUE THREAD

**Issue by Pitterek** [mnaoumov/obsidian-better-markdown-links#12]
### Description

Links do not update after moving file to another directory.

### Steps to Reproduce

1. Open a note
2. Create a new internal link
3. Move this note to another directory
4. Links inside the note are not updated

(see attachment)

### Expected Behavior

Markdown links are updated after file location changed

### Actual Behavior

Markdown links are not updated after file location changed
(see attachment)

### Environment Information

- **Plugin Version**: v2.9.13
- **Obsidian Version**: v1.7.7
- **Operating System**: Linux Mint 21.3

### Attachments

- Please attach a video showing the issue
- Please attach a sample vault where the issue can be reproduced

https://github.com/user-attachments/assets/7aaf707c-120b-4e0a-968a-1b500b76ee87
[test-vault.zip](https://github.com/user-attachments/files/18083882/test-vault.zip)

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by davidmarothi** [comment]
@mnaoumov if a fix for this is made, can you suggest a way to check/fix broken links?

**Comment by mnaoumov** [comment]
Fixed in https://github.com/mnaoumov/obsidian-better-markdown-links/releases/tag/2.9.14

Broken links can be checked via https://github.com/dy-sh/obsidian-consistent-attachments-and-links/
