### ISSUE TITLE
[BUG] Links stays with %20 string instead of a space

### ISSUE THREAD

**Issue by Pitterek** [mnaoumov/obsidian-better-markdown-links#13]
### Description

Links stays with %20 string instead of a space.
Links are not converted at all or are wrong converted

### Steps to Reproduce

1. Open new note
2. Link to another note which has space in the file name
3. Generated Markdown has %20 characters instead of just a space

### Expected Behavior

Links with spaces, as mentioned in project description
[prepare for exam](tag/prepare%20for%20exam.md)  --> [prepare for exam](tag/prepare for exam.md)

### Actual Behavior

%20 string instead of space

### Environment Information

- **Plugin Version**: v2.9.14
- **Obsidian Version**: v1.7.7
- **Operating System**: Linux Mint

### Attachments

- Please attach a video showing the issue
- Please attach a sample vault where the issue can be reproduced

https://github.com/user-attachments/assets/c66bcac2-c58f-4b14-afdf-6b6f3cb5b886

[test-vault.zip](https://github.com/user-attachments/files/18093312/test-vault.zip)

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by Pitterek** [comment]
My settings
![obraz](https://github.com/user-attachments/assets/92b68b83-5218-4d02-a7cf-f8bad0e8cfb8)
![obraz](https://github.com/user-attachments/assets/9f622f30-6830-47d6-a6ae-fc91991ea174)

**Comment by Pitterek** [comment]
It looks like conversion stopped working. 
There are no < > characters inside angle brackets () in markdown link

**Comment by mnaoumov** [comment]
Fixed in https://github.com/mnaoumov/obsidian-better-markdown-links/releases/tag/2.9.15
