### ISSUE TITLE
[FR] Include description in README: how/if this plugin works with "Consistent Attachments and Links"

### ISSUE THREAD

**Issue by growingkittens** [mnaoumov/obsidian-better-markdown-links#14]
### Description

Two main questions to answer in the README:
1. Does "Better Markdown Links" duplicate or extend any features of "Consistent Attachments and Links"?
2. Can/should they be installed together?

### Details

-

### Desired Behavior

-

### Current Behavior

-

### Attachments

- Please attach a video showing the current behavior
- Please attach a sample vault where the desired Feature Request could be applied

### Confirmations

- [X] I attached a video showing the current behavior
- [X] I attached a sample vault where the desired Feature Request could be applied
- [X] I have tested the issue with the latest version
- [X] I have checked for existing Feature Requests

**Comment by mnaoumov** [comment]
README updated

**Comment by mnaoumov** [comment]
Implemented in https://github.com/mnaoumov/obsidian-better-markdown-links/releases/tag/2.10.0
