### ISSUE TITLE
[BUG] Unwanted changes of letter case in link text

### ISSUE THREAD

**Issue by pdolezal** [mnaoumov/obsidian-better-markdown-links#15]
### Description

It seems that if a link text matches the name of the linked file, except the letter case, the text is automatically aligned to the file name. For instance, if the link is `[foo](<./Foo.md>]`, it is converted to `[Foo](<./foo.md>)`. This is not very good as really disturbs the sentences containing such links. The link text should be always honoured.

### Steps to Reproduce

1. Create `foo.md`.
2. Create `bar.md`.
3. Create a link in `foo.md`: `[Bar](<./bar.md>)`
4. The link is converted to `[bar](<./bar.md>)` (the letter case changes)

### Expected Behavior

The link text should be never changed.

### Actual Behavior

The letter case in the link text changes to match the file name of the linked file.

### Environment Information

- **Plugin Version**: 2.10.1
- **Obsidian Version**: 1.7.7
- **Operating System**: Windows 10

### Attachments

- Please attach a video showing the issue
- Please attach a sample vault where the issue can be reproduced

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by mnaoumov** [comment]
Fixed in https://github.com/mnaoumov/obsidian-better-markdown-links/releases/tag/2.10.4
