### ISSUE TITLE
Conversion of png files in a subfolder not quite right

### ISSUE THREAD

**Issue by DutchPete** [mnaoumov/obsidian-better-markdown-links#2]
I have a folder notes, and in that folder there is a subfolder with `.png` files.
The wikilinks format is `![[myImage.png]]`.

When you do the conversion with your plug-in, the format goes to `![](<./myImage.png>)`.
The image cannot be found with that format.

The right markdown format that does find the image is `![](<myImage.png>))`. I found out by playing a bit with the plug-in's conversion format.

Note that conversion of `.md` files works fine, incl. the`./` part. I have not checked what happens with `.pdf` files but suspect it will be like the `.png` files because that is what your focus has been on.

**Comment by mnaoumov** [comment]
@DutchPete, please attach a test vault with the problem. I could not reproduce the issue in mine.

**Comment by mnaoumov** [comment]
Works for me 
![image](https://github.com/user-attachments/assets/aad4996e-f449-4e9f-9795-28b9cf28a536)

**Comment by DutchPete** [comment]
Works for me too, in the sandbox vault. So, the logical conclusion is it is the theme I am using.

However, when I use the default theme in my normal vault AND disable all plug-ins AND disable snippets, it still does not recognize the png image.

Interestingly, when I return to the sandbox vault and enable the theme I am using in my normal vault, it still recognizes the image.

**Comment by mnaoumov** [comment]
@DutchPete yes, it is still worth for me to investigate your problem, because the behavior you experience doesn't match my expectations. Those Obsidian settings that you referred to should affect only creation of new links but the existing links still should work as expected.

That's why I need a copy of the problematic vault for investigation

**Comment by DutchPete** [comment]
My vault is pretty big and has personal files in it.

You stated:
> Those Obsidian settings that you referred to should affect only creation of new links but the existing links still should work as expected.
What I did not say is that I noticed the "problem" after I converted the links in the file using your plug-in. And that conversion happened when the *New link format* setting was still at "Shortest path when possible.

So, it seems to me the "problem" was not really one.

**Comment by mnaoumov** [comment]
@DutchPete based on what you said it seems that my plugin's `Ignore incompatible Obsidian settings` still generates invalid links. I guess it is enough for me to investigate and get it fixed.

Regarding your vault, you could just make a copy and remove almost all the files, keeping just `.obsidian` directory and minimum amount of files necessary to reproduce the issue

**Comment by mnaoumov** [comment]
@DutchPete you were right, my plugin did not work correctly with `Ignore incompatible Obsidian settings`. I fixed that in the release [1.3.0](https://github.com/mnaoumov/obsidian-better-markdown-links/releases/tag/1.3.0). Unfortunately, the incorrect links that my plugin created in your vault, you will have to fix manually

**Comment by DutchPete** [comment]
That is good news; I am glad I was able to contribute a tiny bit to improving the plug-in.

The incorrect links your plug-in created were not numerous, only in 1 file because I was careful to do the conversion vault-wide yet 😀

Thanks again for a great plug-in.
