### ISSUE TITLE
I can't install 

### ISSUE THREAD

**Issue by OPEN1004MIND** [mnaoumov/obsidian-better-markdown-links#4]
I get a message like the one below, saying that the installation was unsuccessful.
Please check.

![MSC230717_095738_001](https://github.com/user-attachments/assets/d46b02f9-baf0-4e9e-a23c-3557f884c5c0)

**Comment by OPEN1004MIND** [comment]
I upgraded to obsidian 1.6.5 and the problem disappeared.

**Comment by mnaoumov** [comment]
Yes, I configured my plugins to work on the latest Obsidian versions
