### ISSUE TITLE
Obsidian on iOS fails to load plugin

### ISSUE THREAD

**Issue by bodby** [mnaoumov/obsidian-better-markdown-links#5]
The following error pops up when trying to enable the plugin. I'm on the latest Obsidian release available (1.6.7):
![image](https://github.com/user-attachments/assets/d835132f-a98a-423c-a8ff-a8d970979d1f)
I apologize for not sending any logs; I have no idea where these are stored on my phone.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/mnaoumov/obsidian-better-markdown-links/releases/tag/2.4.0

**Comment by bodby** [comment]
Thanks for the quick response!
