### ISSUE TITLE
When a file is renamed, the links in the file are not automatically modified

### ISSUE THREAD

**Issue by at2008** [mnaoumov/obsidian-better-markdown-links#6]
Test situation: Place 1 embed image file link and 1 embed non-image file link in the document. Rename the file. The image file link can automatically change the link, while the non-image file link does not change. Rename the file again and both links will remain unchanged.

In addition, when converting from wikilink to markdown format, I want to use the file name as linkText, rather than the path name + file name as linkText.

**Comment by at2008** [comment]
I found that this plugin may automatically convert all [text](link) to [text](<link>). This can be risky and inefficient.

Changing the format of all links in a document can be done as a new independent command.

**Comment by mnaoumov** [comment]
1. Cannot reproduce the issue. Please provide the test vault and the video with the issue
2. If you don't like automatic conversion, disable them in the settings

![image](https://github.com/user-attachments/assets/94e2be38-e597-4088-9b84-b5f4c7918771)

**Comment by at2008** [comment]
Thanks for your reply, I tested it again, and now the situation is: these two plug-ins are enabled together, and are set as follows. There are no longer any problems mentioned above, and everything seems to be fine.

![image](https://github.com/user-attachments/assets/99576d55-3b73-406a-a4df-830160b3c521)


![image](https://github.com/user-attachments/assets/66348220-c167-48ba-9dc7-1851cc4de3d6)

Thank you very much!

**Comment by mnaoumov** [comment]
I could not reproduce the problem, you confirmed that everything works with the right settings, and automatic conversion can already be turned off in the settings.
