### ISSUE TITLE
Request: Can the plugin add an option to automatically get the link file name as the caption when pasting an image? 

### ISSUE THREAD

**Issue by at2008** [mnaoumov/obsidian-better-markdown-links#7]
Request: Can the plugin add an option to automatically get the link file name as the caption when pasting an image? 

Now it is like this:

`![](<./path/filename.png>)`

Hope it can be like this:

`![filename.png](<./path/filename.png>)`

**Comment by mnaoumov** [comment]
Are you sure you want add extension? Markdown links by default are added without `.md`

**Comment by at2008** [comment]
OK, then don't add the extension.

**Comment by mnaoumov** [comment]
Implemented in https://github.com/mnaoumov/obsidian-better-markdown-links/releases/tag/2.6.0
