### ISSUE TITLE
`Convert links in current file` command issue

### ISSUE THREAD

**Issue by at2008** [mnaoumov/obsidian-better-markdown-links#8]
The `Convert links in current file` command does not seem to work if there are spaces in the markdown link.

`[test.json](./te st/test.json)`

Will not be converted to the following format

`[test.json](<./te st/test.json>)`

**Comment by mnaoumov** [comment]
The first link is invalid markdown, it cannot contain spaces

The correct link is

`[test.json](./te%20st/test.json)`

**Comment by mnaoumov** [comment]
A markdown link path cannot contain unescaped spaces, so `./te st/test.json` is not a valid link to convert. The correct form is `./te%20st/test.json`.
